# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

[harvest]
sources = ["cff", "git"]
sop = "asdfgh"

[harvest.cff]
enable_validation = false

[deposit]
target = "sopejiof"

[deposit.invenio_rdm]
site_url = "https://sandbox.zenodo.org"
communities = ["zenodo"]
access_right = "open"
